[project]
name = "openBES"
version = "0.1.0"
description = "Python implementation of the Open Building Energy Simulation (OpenBES) tool."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
]
