[project]
name = "openBES"
version = "0.1.1"
description = "Python implementation of the Open Building Energy Simulation (OpenBES) tool."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "pvlib",
]

[project.optional-dependencies]
jit = ["numba"]
dev = [
    "line_profiler",
    "numba",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["openbes*"]

[build-system]
requires = ["setuptools>=61", "wheel", "build"]
build-backend = "setuptools.build_meta"
