[project]
name = "openBES"
version = "0.3.3"
description = "Python implementation of the Open Building Energy Simulation (OpenBES) tool."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2",
    "pandas",
    "pvlib",
    "pydantic>=2.7"
]

[project.optional-dependencies]
jit = ["numba"]
dev = [
    "line_profiler",
    "numba",
    "datamodel-code-generator>=0.43",
    "ruff",
    "jsonschema>=4"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["openbes*"]

[tool.setuptools.package-data]
openbes = [
    "**/lighting_data/*.csv",
    "**/epw_data/*.epw",
    "**/example_data/*.json",
    "**/schemas/*.json",
    "**/report_data/*.csv"
]

[build-system]
requires = ["setuptools>=61", "wheel", "build"]
build-backend = "setuptools.build_meta"

[tool.datamodel-codegen]
class-name = "OpenBESCase"
formatters = ["ruff-format"]
input = "src/openbes/schemas/OpenBES.schema.json"
input-file-type = "jsonschema"
keyword-only = true
output = "src/openbes/schemas/generated/models.py"
output-model-type = "pydantic_v2.BaseModel"
target-python-version = "3.11"
use-default-kwarg = true
use-double-quotes = true
use-standard-collections = true