"d.advanced_heat_capacity_am" = 2
"d.air_heat_capacity" = 2783.2518000000005
"d.altitude" = 1650
"d.appliance_on_off" = 1
"d.cooling_load_factor" = 1
"d.cooling_system1_min_demand" = 10
"d.cooling_system2_energy_efficifiency_ratio" = ""
"d.cooling_system2_energy_source" = "Electricity"
"d.cooling_system2_min_demand" = ""
"d.cooling_system2_nominal_capacity" = ""
"d.cooling_system2_number" = ""
"d.cooling_system2_off_time" = ""
"d.cooling_system2_on_time" = ""
"d.cooling_system2_sensible_nominal_capacity" = ""
"d.cooling_system2_simultaneity_factor_canteen" = ""
"d.cooling_system2_simultaneity_factor_common" = ""
"d.cooling_system2_simultaneity_factor_office" = ""
"d.cooling_system2_simultaneity_factor_other" = ""
"d.cooling_system2_simultaneity_factor_teaching" = ""
"d.cooling_system2_type" = ""
"d.courtyard_length" = 0
"d.courtyard_number" = 0
"d.courtyard_width" = 0
"d.density_of_air" = 1.0156
"d.facade_absorption_coefficient" = 0.6
"d.facade_correction_factor" = 1
"d.facade_emissivity" = 0.9
"d.floor_correction_factor" = 1
"d.heat_capacity_correction_factor" = 1
"d.heat_capacity_joule" = 54010.7
"d.heating_load_factor" = 1
"d.heating_system1_min_demand" = 35
"d.heating_system2_efficiency_cop" = ""
"d.heating_system2_energy_source" = "Natural gas"
"d.heating_system2_min_demand" = 0.2
"d.heating_system2_nominal_capacity" = ""
"d.heating_system2_number" = ""
"d.heating_system2_off_time" = 4
"d.heating_system2_on_time" = 4
"d.heating_system2_simultaneity_factor_canteen" = ""
"d.heating_system2_simultaneity_factor_common" = ""
"d.heating_system2_simultaneity_factor_office" = ""
"d.heating_system2_simultaneity_factor_other" = ""
"d.heating_system2_simultaneity_factor_teaching" = ""
"d.heating_system2_type" = ""
"d.infiltration_correction_factor" = 1
"d.leakage_air_flow_dependent" = 0
"d.lighting_on_off" = 0
"d.nia_gba_ratio" = 1
"d.occupancy_close_common" = 24
"d.occupancy_close_other" = 24
"d.occupancy_on_off" = 0
"d.occupancy_open_common" = 1
"d.occupancy_open_other" = 1
"d.open_courtyard_depth_a1" = 0
"d.open_courtyard_depth_b1" = 0
"d.open_courtyard_depth_c1" = 0
"d.open_courtyard_depth_d1" = 0
"d.open_courtyard_number_a1" = 0
"d.open_courtyard_number_b1" = 0
"d.open_courtyard_number_c1" = 0
"d.open_courtyard_number_d1" = 0
"d.pressure_of_air" = 83460
"d.roof_absorption_coefficient" = 0.6
"d.roof_correction_factor" = 1
"d.roof_emissivity" = 0.9
"d.shading_correction_factor" = 1
"d.specific_heat_of_air" = 1.015
"d.temperature_tolerance" = 0
"d.ventilation_system2_airflow" = ""
"d.ventilation_system2_energy_source" = "Electricity"
"d.ventilation_system2_heat_recovery_efficiency" = 0
"d.ventilation_system2_off_time" = ""
"d.ventilation_system2_on_time" = ""
"d.ventilation_system2_rated_input_power" = 0
"d.ventilation_system2_type" = "Air handling unit"
"d.ventilation_system2_ventilated_area" = ""
"d.view_factor_to_sky_facade" = 0.5
"d.view_factor_to_sky_roof" = 1
"d.window_correction_factor" = 1
"i.appliances_load" = 4.16666666666667
"i.biomass_annual" = ""
"i.biomass_pellets_annual" = ""
"i.building_area" = "ASHRAE_140"
"i.building_height" = 2.7
"i.building_length" = 8
"i.building_name" = "Case 600"
"i.building_standby_load" = ""
"i.building_type" = "n/a"
"i.building_width" = 6
"i.condition_z1" = "Conditioned"
"i.condition_z2" = "Conditioned"
"i.condition_z3" = "Conditioned"
"i.condition_z4" = "Conditioned"
"i.condition_z5" = "Unconditioned"
"i.cooling_system1_energy_efficifiency_ratio" = 0
"i.cooling_system1_energy_source" = "Electricity"
"i.cooling_system1_nominal_capacity" = 0
"i.cooling_system1_number" = 1
"i.cooling_system1_off_time" = 9
"i.cooling_system1_on_time" = 9
"i.cooling_system1_sensible_nominal_capacity" = 0
"i.cooling_system1_simultaneity_factor_canteen" = 0
"i.cooling_system1_simultaneity_factor_common" = ""
"i.cooling_system1_simultaneity_factor_office" = 0
"i.cooling_system1_simultaneity_factor_other" = ""
"i.cooling_system1_simultaneity_factor_teaching" = 0
"i.cooling_system1_type" = "Heat pump"
"i.country" = "Other"
"i.diesel_annual" = ""
"i.electricity_annual" = ""
"i.electricity_april" = ""
"i.electricity_august" = ""
"i.electricity_december" = ""
"i.electricity_february" = ""
"i.electricity_january" = ""
"i.electricity_july" = ""
"i.electricity_june" = ""
"i.electricity_march" = ""
"i.electricity_may" = ""
"i.electricity_november" = ""
"i.electricity_october" = ""
"i.electricity_september" = ""
"i.energy_generated" = 0
"i.energy_used" = 0
"i.first_floor_area_z1" = ""
"i.first_floor_area_z2" = ""
"i.first_floor_area_z3" = ""
"i.first_floor_area_z4" = ""
"i.first_floor_area_z5" = ""
"i.floor_to_ceiling_height" = 2.7
"i.fourth_floor_area_z1" = ""
"i.fourth_floor_area_z2" = ""
"i.fourth_floor_area_z3" = ""
"i.fourth_floor_area_z4" = ""
"i.fourth_floor_area_z5" = ""
"i.gas_april" = ""
"i.gas_august" = ""
"i.gas_december" = ""
"i.gas_february" = ""
"i.gas_january" = ""
"i.gas_july" = ""
"i.gas_june" = ""
"i.gas_march" = ""
"i.gas_may" = ""
"i.gas_november" = ""
"i.gas_october" = ""
"i.gas_september" = ""
"i.ground_floor_area_z1" = 48
"i.ground_floor_area_z2" = ""
"i.ground_floor_area_z3" = ""
"i.ground_floor_area_z4" = ""
"i.ground_floor_area_z5" = ""
"i.heat_capacity" = "Custom Value"
"i.heating_system1_efficiency_cop" = 0
"i.heating_system1_energy_source" = "Natural gas"
"i.heating_system1_nominal_capacity" = 0
"i.heating_system1_number" = 1
"i.heating_system1_off_time" = 8
"i.heating_system1_on_time" = 8
"i.heating_system1_simultaneity_factor_canteen" = 0
"i.heating_system1_simultaneity_factor_common" = 0
"i.heating_system1_simultaneity_factor_office" = 0
"i.heating_system1_simultaneity_factor_other" = 0
"i.heating_system1_simultaneity_factor_teaching" = 0
"i.heating_system1_type" = "Condensing boiler"
"i.holiday" = "Yes"
"i.leakage_air_flow" = 0
"i.leakage_air_flow_independent" = 1.35
"i.lighting_control" = "Manual"
"i.lighting_off_time" = 17
"i.lighting_on_time" = 9
"i.lighting_simultaneity_factor" = 0.2
"i.lighting_system_ballast_z1" = ""
"i.lighting_system_ballast_z2" = ""
"i.lighting_system_ballast_z3" = ""
"i.lighting_system_ballast_z4" = ""
"i.lighting_system_ballast_z5" = ""
"i.lighting_system_ballast_z6" = ""
"i.lighting_system_lamp_number_z1" = ""
"i.lighting_system_lamp_number_z2" = ""
"i.lighting_system_lamp_number_z3" = ""
"i.lighting_system_lamp_number_z4" = ""
"i.lighting_system_lamp_number_z5" = ""
"i.lighting_system_lamp_number_z6" = ""
"i.lighting_system_lamp_power_z1" = ""
"i.lighting_system_lamp_power_z2" = ""
"i.lighting_system_lamp_power_z3" = ""
"i.lighting_system_lamp_power_z4" = ""
"i.lighting_system_lamp_power_z5" = ""
"i.lighting_system_lamp_power_z6" = ""
"i.lighting_system_luminary_number_z1" = ""
"i.lighting_system_luminary_number_z2" = ""
"i.lighting_system_luminary_number_z3" = ""
"i.lighting_system_luminary_number_z4" = ""
"i.lighting_system_luminary_number_z5" = ""
"i.lighting_system_luminary_number_z6" = ""
"i.lighting_system_name_z1" = ""
"i.lighting_system_name_z2" = ""
"i.lighting_system_name_z3" = ""
"i.lighting_system_name_z4" = ""
"i.lighting_system_name_z5" = ""
"i.lighting_system_name_z6" = ""
"i.lighting_system_operating_hours_z1" = ""
"i.lighting_system_operating_hours_z2" = ""
"i.lighting_system_operating_hours_z3" = ""
"i.lighting_system_operating_hours_z4" = ""
"i.lighting_system_operating_hours_z5" = ""
"i.lighting_system_operating_hours_z6" = ""
"i.lighting_system_similar_zone_number_z1" = ""
"i.lighting_system_similar_zone_number_z2" = ""
"i.lighting_system_similar_zone_number_z3" = ""
"i.lighting_system_similar_zone_number_z4" = ""
"i.lighting_system_similar_zone_number_z5" = ""
"i.lighting_system_similar_zone_number_z6" = ""
"i.lighting_system_simultaneity_factor_z1" = ""
"i.lighting_system_simultaneity_factor_z2" = ""
"i.lighting_system_simultaneity_factor_z3" = ""
"i.lighting_system_simultaneity_factor_z4" = ""
"i.lighting_system_simultaneity_factor_z5" = ""
"i.lighting_system_simultaneity_factor_z6" = ""
"i.lighting_system_tech_z1" = ""
"i.lighting_system_tech_z2" = ""
"i.lighting_system_tech_z3" = ""
"i.lighting_system_tech_z4" = ""
"i.lighting_system_tech_z5" = ""
"i.lighting_system_tech_z6" = ""
"i.location" = "Denver"
"i.LPG_annual" = ""
"i.max_building_occupation" = 1
"i.meteorological_file" = "725650_Denver"
"i.natural_gas_annual" = ""
"i.natural_ventilation_night" = 0
"i.occupancy_close_canteen" = 24
"i.occupancy_close_office" = 24
"i.occupancy_close_teaching" = 24
"i.occupancy_open_canteen" = 1
"i.occupancy_open_office" = 1
"i.occupancy_open_teaching" = 1
"i.orientation_angle" = 0
"i.other_electricity_usage" = ""
"i.other_gas_usage" = 0
"i.roof_angle" = 0
"i.schedule_april" = 1
"i.schedule_august" = 1
"i.schedule_december" = 1
"i.schedule_february" = 1
"i.schedule_friday" = 1
"i.schedule_january" = 1
"i.schedule_july" = 1
"i.schedule_june" = 1
"i.schedule_march" = 1
"i.schedule_may" = 1
"i.schedule_monday" = 1
"i.schedule_november" = 1
"i.schedule_october" = 1
"i.schedule_saturday" = 1
"i.schedule_september" = 1
"i.schedule_sunday" = 1
"i.schedule_thursday" = 1
"i.schedule_tuesday" = 1
"i.schedule_wednesday" = 1
"i.second_floor_area_z1" = ""
"i.second_floor_area_z2" = ""
"i.second_floor_area_z3" = ""
"i.second_floor_area_z4" = ""
"i.second_floor_area_z5" = ""
"i.setpoint_summer_day" = 27
"i.setpoint_summer_night" = 27
"i.setpoint_winter_day" = 20
"i.setpoint_winter_night" = 20
"i.slab_thickness" = 0
"i.solar_external_shading_summer" = 1
"i.solar_external_shading_winter" = 1
"i.terrain_class" = "Open terrain"
"i.thermal_bridge_facade_ground" = "No"
"i.thermal_bridge_facade_intermediate" = "No"
"i.thermal_bridge_facade_roof" = "No"
"i.thermal_bridge_shading" = "No"
"i.thermal_bridge_window" = "No"
"i.third_floor_area_z1" = ""
"i.third_floor_area_z2" = ""
"i.third_floor_area_z3" = ""
"i.third_floor_area_z4" = ""
"i.third_floor_area_z5" = ""
"i.typical_occupation" = 1
"i.uvalue_facade" = 0.06999999999999999
"i.uvalue_floor" = 0.039
"i.uvalue_roof" = 0.09
"i.uvalue_window" = 2.74
"i.ventilation_system1_airflow" = ""
"i.ventilation_system1_energy_source" = "Electricity"
"i.ventilation_system1_heat_recovery_efficiency" = 0
"i.ventilation_system1_off_time" = ""
"i.ventilation_system1_on_time" = ""
"i.ventilation_system1_rated_input_power" = 0
"i.ventilation_system1_type" = "Air handling unit"
"i.ventilation_system1_ventilated_area" = ""
"i.water_demand" = 0
"i.water_reference_temperature" = 60
"i.water_supply_temperature" = 16
"i.water_system_efficiency_cop" = 0
"i.water_system_energy_source" = "Electricity"
"i.water_system_nominal_capacity" = 0
"i.water_system_type" = "Electric boiler"
"i.window_frame_factor" = 0
"i.window_gvalue" = 0.739
"i.window_height" = 2
"i.window_length" = 3
"i.window_number_first_a1" = 0
"i.window_number_first_b1" = 0
"i.window_number_first_c1" = 0
"i.window_number_first_d1" = 0
"i.window_number_fourth_a1" = 0
"i.window_number_fourth_b1" = 0
"i.window_number_fourth_c1" = 0
"i.window_number_fourth_d1" = 0
"i.window_number_ground_a1" = 0
"i.window_number_ground_b1" = 0
"i.window_number_ground_c1" = 2
"i.window_number_ground_d1" = 0
"i.window_number_second_a1" = 0
"i.window_number_second_b1" = 0
"i.window_number_second_c1" = 0
"i.window_number_second_d1" = 0
"i.window_number_third_a1" = 0
"i.window_number_third_b1" = 0
"i.window_number_third_c1" = 0
"i.window_number_third_d1" = 0
"i.zone_name_z1" = "Office area"
"i.zone_name_z2" = "Teaching"
"i.zone_name_z3" = "Canteen"
"i.zone_name_z4" = "Common areas"
"i.zone_name_z5" = "Other spaces"
