import json
from importlib.resources import files

from .generated.models import (
    Ballast,
    Building,
    Consumption,
    COOLINGSYSTEMTYPES,
    CoolingSystem,
    Duration,
    ENERGYSOURCES,
    HEATINGSYSTEMTYPES,
    HeatingSystem,
    HotWaterSystem,
    HourPeak,
    LightingControl,
    LightingSystem,
    LightingSystemTech,
    METEOROLOGICALFILE,
    ModelValidation,
    OpenBESCase,
    OpenBESMetaData,
    OpenBESOutput,
    OpenBESParameters as OpenBESParametersV2,
    OpenBESSpecification as OpenBESSpecificationV2,
    OccupationSchedule,
    Range,
    SpaceThermalDemandResult,
    TERRAINCLASS,
    ThermalSystemResult,
    VentilationSystem,
    VentilationSystemResult,
    Zone,
    ZoneSimultaneity,
)
from .conversion import toml_to_json, json_to_toml

with open(str(files("openbes.schemas") / "OpenBES.schema.json"), "r") as json_file:
    SPECIFICATION = json.load(json_file)
    SPECIFICATION_VERSION = SPECIFICATION["$version"]

__all__ = [
    "Ballast",
    "Building",
    "Consumption",
    "COOLINGSYSTEMTYPES",
    "CoolingSystem",
    "Duration",
    "ENERGYSOURCES",
    "HEATINGSYSTEMTYPES",
    "HeatingSystem",
    "HotWaterSystem",
    "HourPeak",
    "LightingControl",
    "LightingSystem",
    "LightingSystemTech",
    "METEOROLOGICALFILE",
    "ModelValidation",
    "OpenBESCase",
    "OpenBESMetaData",
    "OpenBESOutput",
    "OpenBESParametersV2",
    "OpenBESSpecificationV2",
    "OccupationSchedule",
    "Range",
    "SpaceThermalDemandResult",
    "TERRAINCLASS",
    "ThermalSystemResult",
    "VentilationSystem",
    "VentilationSystemResult",
    "Zone",
    "ZoneSimultaneity",
    "toml_to_json",
    "json_to_toml",
    "SPECIFICATION",
    "SPECIFICATION_VERSION",
]
